modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="tst"
version="1.0.0"
displayName="tinker_scc_tool"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ecmbinshu"

[[dependencies.tst]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.tst]]
    modId="tconstruct"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tst]]
    modId="scc"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tst]]
    modId="mantle"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tst]]
    modId="ascc"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


